### ISSUE TITLE
errore modalità EASY

### ISSUE THREAD

**Issue by unozer** [Maghetto666/bandiere#4]
Ho selezionato Svizzera ma non gli è piaciuto

![image](https://github.com/Maghetto666/bandiere/assets/40232537/5b54d7e0-d8d1-4ec8-b1e0-106fed25ac1c)

**Comment by Maghetto666** [comment]
Ciao, grazie per la segnalazione! Il bug riguardava una vecchia versione del programma, ora dovresti trovare tutto risolto.

Continua a seguirci!
